#!/usr/bin/env bash
exec docker run --rm -i --user "$(id -u)" --volume "$HOME/.triton:/home/node/.triton" --volume "$HOME/.ssh:/home/node/.ssh:ro" --entrypoint "/usr/local/bin/$(basename "$0")" mookas/triton-cli "$@"
